#!/bin/sh

cp packages-sample.el packages.el

if ! grep -q 'GENERATED BY EMACS-CONFIG' ~/.emacs 2> /dev/null; then
    echo ';; GENERATED BY EMACS-CONFIG' >> ~/.emacs
    echo '(load-file "~/emacs-config/init.el")' >> ~/.emacs

    echo 'Installed to your ~/.emacs file. Please verify that everything is OK.'
fi

